add Parser [all fixes available in update-parser branch]
Revarine/Modsen-practice pull request #3
Opened 2024-06-20 13:08 UTC by Ryu-ko

I added a folder with Parser and fixed an error with buttons in MainWindow.xaml.cs  in numberButton_Click()

2024-06-21 19:37 UTC, mebry requested changes

2024-06-21 19:37 UTC, mebry commented on calculator/calculator/calculator/ParserF/Expression.cs
> +    public class BinaryExpression : Expression //само выражение
Write in English

2024-06-21 19:37 UTC, mebry commented on calculator/calculator/calculator/Views/MainWindow.xaml.cs
> +                //Console.WriteLine($"Parsed Expression Tree: {expression}");
If you don't need this code, delete it

2024-06-21 19:37 UTC, mebry commented on calculator/calculator/calculator/ParserF/Computations.cs
> +                        throw new Exception("Unknown operator: " + binaryExpr.Operator);
it is better to use more specific types of exceptions

2024-06-21 19:37 UTC, mebry commented on calculator/calculator/calculator/ParserF/Parser.cs
> +                Console.WriteLine($"Parsed Term: {left}");
clean the code from such code, especially in cycles

2024-06-21 19:37 UTC, mebry commented on calculator/calculator/calculator/ParserF/Token.cs
> +        }
You can put it in a separate file

2024-06-22 15:10 UTC, Ryu-ko commented on calculator/calculator/calculator/ParserF/Expression.cs
> +    public class BinaryExpression : Expression //само выражение
Fixed in branch UpdateParser

2024-06-22 15:10 UTC, Ryu-ko commented on calculator/calculator/calculator/Views/MainWindow.xaml.cs
> +                //Console.WriteLine($"Parsed Expression Tree: {expression}");
Fixed in branch UpdateParser

2024-06-22 15:14 UTC, Ryu-ko commented on calculator/calculator/calculator/ParserF/Computations.cs
> +                        throw new Exception("Unknown operator: " + binaryExpr.Operator);
I added new class for Exceptions and change the same lines. We will improve Exception handling later. (changes in branch UpdateParser)

2024-06-22 15:15 UTC, Ryu-ko commented on calculator/calculator/calculator/ParserF/Parser.cs
> +                Console.WriteLine($"Parsed Term: {left}");
Fixed in branch UpdateParser

2024-06-22 15:16 UTC, Ryu-ko commented on calculator/calculator/calculator/ParserF/Token.cs
> +        }
Fixed in branch UpdateParser

2024-06-22 18:50 UTC, merged