Merge from functions branch to develop
Revarine/Modsen-practice pull request #4
Opened 2024-06-20 19:06 UTC by Revarine

2024-06-21 19:44 UTC, mebry requested changes

2024-06-21 19:44 UTC, mebry commented on calculator/calculator/calculator/Views/AddFunction.xaml.cs
> +            string functionName = FunctionNameTextBox.Text;
Why var is not used. Other places in the application use var. Fix it everywhere

2024-06-21 19:44 UTC, mebry commented on calculator/calculator/calculator/Views/AddFunction.xaml.cs
> +                MessageBox.Show("В названии функции могуть быть только буквы или цифры, начинаться оно должно с буквы.");
In English

2024-06-21 20:06 UTC, Revarine commented on calculator/calculator/calculator/Views/AddFunction.xaml.cs
> +            string functionName = FunctionNameTextBox.Text;
Fixed in last commit ✅

2024-06-21 20:07 UTC, Revarine commented on calculator/calculator/calculator/Views/AddFunction.xaml.cs
> +                MessageBox.Show("В названии функции могуть быть только буквы или цифры, начинаться оно должно с буквы.");
Fixed in last commit ✅

2024-06-22 15:53 UTC, mebry approved these changes

2024-06-22 18:51 UTC, merged